---
name: elder_care

channels:
  - conda-forge
  - defaults

dependencies:
  - python=3.10
  - pip
  - setuptools_scm
  - toml

  # Reproducibility
  - conda-lock

  # Package dependencies
  - estimagic
  - jax
  - numpy
  - numba
  - pandas
  - networkx
  - pandas
  - plotly
  - pytask
  - scipy

  # Misc
  - black
  - nb_black
  - pdbpp
  - pre-commit
  - pytest
  - pytest-cov
  - pytest-xdist
  - tox-conda

  # Jupyter
  - jupyterlab
  - jupyter-lsp=2.2.0
  - jupyter_client=8.3.0
  - jupyter_contrib_nbextensions=0.7.0
  - jupyter_core=5.3.1
  - jupyter_events=0.7.0
  - jupyter_highlight_selected_word=0.2.0
  - jupyter_latex_envs=1.4.6
  - jupyter_server=2.5.0
  - jupyter_server_terminals=0.4.4

  - pip:
    - jupyter==1.0.0
    - jupyter-console==6.6.3
    - jupyter-contrib-core==0.4.2
    - jupyter-nbextensions-configurator==0.6.3

    - blackcellmagic
    - furo

    # local installation
    - -e .
